### PR TITLE
incorrect fonts

### PR DESCRIPTION
**Pull request by harshal2608**
#310

### CODE REVIEW

**Comment by iamoskvin** [comment]
1. I see that fonts are rendered differently in the current version and in the proposed one.
Could you check it, please?
Please, pay attention on the chars height in the navbar
image
image

2. Why did you comment out all font-weights except for two most frequent? 
Currently we use other font-weights too. Example:
image
image

3. Would it make sense to replace the DM-Sans font from the CDN to our file too? To ensure that it can't be blocked like it was for other CDN. What do you think?

**Comment by harshal2608** [comment]
I think the first two are related. so the fonts need a woff file which i could only find for the two weights. I think i we could find and add all the weights it will be fixed.

For the third point. I think we are using googlefonts for DM Sans. which are very common so i dont see it being a problem

**Comment by iamoskvin** [comment]
> I think the first two are related. so the fonts need a woff file which i could only find for the two weights. I think i we could find and add all the weights it will be fixed.
Probably, not. We have font-weight 750 in the navbar and we have it in the css.
And why do you search font files and not grab exactly the same fonts that we use from https://fonts.cdnfonts.com/css/avenir-lt-std? What am I missing? We have urls in this file that point out to woffs.

So, it looks like we just use fonts that are not the same as original.

> For the third point. I think we are using googlefonts for DM Sans. which are very common so i dont see it being a problem
I don't know. Yes, google fonts are common. But we also faced an issue that some ISP providers blocked github content, for example. So, I am just suggesting to move all possible stuff from third-parties urls to escape such problems.
@rohitgoyal what do you think about this? Is it a good idea or a waste of time now?

**Comment by harshal2608** [comment]
> Probably, not. We have font-weight 750 in the navbar and we have it in the css. And why do you search font files and not grab exactly the same fonts that we use from https://fonts.cdnfonts.com/css/avenir-lt-std What am I missing? We have urls in this file that point out to woffs. So, it looks like we just use fonts that are not the same as original.

those urls are also of cdnfonts which gives 304.

**Comment by iamoskvin** [comment]
> > Probably, not. We have font-weight 750 in the navbar and we have it in the css. And why do you search font files and not grab exactly the same fonts that we use from https://fonts.cdnfonts.com/css/avenir-lt-std What am I missing? We have urls in this file that point out to woffs. So, it looks like we just use fonts that are not the same as original.
> 
> those urls are also of cdnfonts which gives 304.

Sorry, maybe I did not explain in detail. We could just download font files from these urls. At least, I can download them without problem. And then put files in the app src as you did.

**Comment by harshal2608** [comment]
That is absolutely correct. Thanks @iamoskvin . Added all of them now

**Pull request merged**
